[workspace]
members = [
]
[package]
name = "unsafe-libh3"
authors = ["C2Rust"]
version = "0.0.0"
publish = false
edition = "2021"
autobins = false

[lib]
name = "unsafe_libh3"
path = "lib.rs"
crate-type = ["staticlib", "rlib"]
[dependencies]
num-traits= "0.2"
libc= "0.2"
