
[package]
name = "unsafe-h3lib"
authors = ["C2Rust"]
version = "0.0.0"
publish = false
edition = "2021"
autobins = false

[lib]
name = "unsafe_h3lib"
path = "lib/lib.rs"
crate-type = ["staticlib", "rlib"]

[dependencies]
num-traits= "0.2"
libc= "0.2"